"""Adiciona tabelas de Nota Fiscal

Revision ID: 1338a23737d9
Revises: d73f57411eda
Create Date: 2025-05-23 15:41:20.182635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1338a23737d9'
down_revision = 'd73f57411eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('cnpj_emitente', sa.String(length=20), nullable=False),
    sa.Column('cnpj_destinatario', sa.String(length=20), nullable=False),
    sa.Column('chave_acesso', sa.String(length=50), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso')
    )
    op.create_table('nota_fiscal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['nota_fiscal.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_fiscal_item')
    op.drop_table('nota_fiscal')
    # ### end Alembic commands ###
