"""Adiciona campo marca em Produto

Revision ID: cfb4bf61aa0f
Revises: e7b79ee9c66b
Create Date: 2025-05-23 16:32:38.667748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb4bf61aa0f'
down_revision = 'e7b79ee9c66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
