"""Remove tabelas de nota fiscal

Revision ID: e7b79ee9c66b
Revises: 1338a23737d9
Create Date: 2025-05-23 15:50:02.911266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b79ee9c66b'
down_revision = '1338a23737d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_fiscal_item')
    op.drop_table('nota_fiscal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nota_fiscal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=20), nullable=False),
    sa.Column('serie', sa.VARCHAR(length=10), nullable=False),
    sa.Column('data_emissao', sa.DATE(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('cnpj_emitente', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cnpj_destinatario', sa.VARCHAR(length=20), nullable=False),
    sa.Column('chave_acesso', sa.VARCHAR(length=50), nullable=False),
    sa.Column('valor_total', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso')
    )
    op.create_table('nota_fiscal_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nota_fiscal_id', sa.INTEGER(), nullable=False),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('valor_unitario', sa.FLOAT(), nullable=False),
    sa.Column('valor_total', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['nota_fiscal.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
